INSERT INTO player (player_name) 
VALUES 	('GOL CONTRA - AZUL'),
		('GOL CONTRA - VERMELHO'),
		('CAIO'),
		('DANILO'),
		('DIEGO SCHIMIDEL'),
		('DOUGLAS'),
		('DUDU'),
		('FELIPE CASOTTI'),
		('GUILHERME'),
		('JOÃO PEDRO'),
		('LECAO'),
		('MATHEUS DE BONE'),
		('PEDRO LUCAS'),
		('RAFAEL'),
		('RAPHINHA'),
		('RAYNER'),
		('RODRIGO'),
		('VINICIUS'),
		('WALLACE'),
		('WALTER'),
		('YURI'),
		('LORRAN (GOLEIRO)'),
		('RAPHAEL GRIPP (GOLEIRO)'),
		('VINICIUS (GOLEIRO)'),
		('WILLES (GOLEIRO)');